export const metricsDict = {
  operating_revenue: "Operating Revenue",
  total_revenue: "Total Revenue",
  cost_of_revenue: "Cost of Revenue",
  gross_profit: "Gross Profit",
  selling_general_and_admin_expense:
    "Selling, General, and Administrative Expense",
  research_and_development_expense: "Research and Development Expense",
  operating_expense: "Operating Expense",
  operating_income: "Operating Income",
  interest_income_non_operating: "Interest Income (Non-Operating)",
  interest_expense_non_operating: "Interest Expense (Non-Operating)",
  net_non_operating_interest_income_expense:
    "Net Non-Operating Interest Income (Expense)",
  other_non_operating_income_expenses: "Other Non-Operating Income (Expenses)",
  other_income_expense: "Other Income (Expense)",
  total_pre_tax_income: "Total Pre-Tax Income",
  tax_provision: "Tax Provision",
  net_income_continuous_operations: "Net Income from Continuous Operations",
  net_income_including_noncontrolling_interests:
    "Net Income Including Noncontrolling Interests",
  net_income: "Net Income",
  net_income_attributable_to_common_shareholders:
    "Net Income Attributable to Common Shareholders",
  diluted_ni_availto_com_stockholders:
    "Diluted NI Available to Common Stockholders",
  basic_earnings_per_share: "Basic Earnings per Share",
  diluted_earnings_per_share: "Diluted Earnings per Share",
  weighted_average_basic_shares_outstanding:
    "Weighted Average Basic Shares Outstanding",
  weighted_average_diluted_shares_outstanding:
    "Weighted Average Diluted Shares Outstanding",
  total_operating_income_as_reported: "Total Operating Income (As Reported)",
  total_expenses: "Total Expenses",
  net_income_from_continuing_and_discontinued_operation:
    "Net Income from Continuing and Discontinued Operation",
  normalized_income: "Normalized Income",
  interest_income: "Interest Income",
  interest_expense: "Interest Expense",
  net_interest_income: "Net Interest Income",
  ebit: "EBIT",
  ebitda: "EBITDA",
  reconciled_cost_of_revenue: "Reconciled Cost of Revenue",
  reconciled_depreciation: "Reconciled Depreciation",
  net_income_from_continuing_operation_net_minority_interest:
    "Net Income from Continuing Operation Net Minority Interest",
  normalized_ebitda: "Normalized EBITDA",
  tax_rate_for_calcs: "Tax Rate for Calculations",
  tax_effect_of_unusual_items: "Tax Effect of Unusual Items",

  cash_financial: "Cash Financial",
  cash_equivalents: "Cash Equivalents",
  cash_and_cash_equivalents: "Cash and Cash Equivalents",
  short_term_investments: "Short-Term Investments",
  cash_cash_equivalents_and_short_term_investments:
    "Cash, Cash Equivalents, and Short-Term Investments",
  accounts_receivable: "Accounts Receivable",
  other_receivables: "Other Receivables",
  net_receivables: "Net Receivables",
  inventories: "Inventories",
  other_current_assets: "Other Current Assets",
  total_current_assets: "Total Current Assets",
  properties: "Properties",
  land_and_improvements: "Land and Improvements",
  machinery_furniture_equipment: "Machinery, Furniture, and Equipment",
  other_properties: "Other Properties",
  leases: "Leases",
  plant_property_equipment_gross: "Plant, Property, and Equipment (Gross)",
  accumulated_depreciation: "Accumulated Depreciation",
  plant_property_equipment_net: "Plant, Property, and Equipment (Net)",
  available_for_sale_securities: "Available-for-Sale Securities",
  investmentin_financial_assets: "Investment in Financial Assets",
  other_investments: "Other Investments",
  investments_and_advances: "Investments and Advances",
  non_current_deferred_taxes_assets: "Non-Current Deferred Taxes Assets",
  non_current_deferred_assets: "Non-Current Deferred Assets",
  other_non_current_assets: "Other Non-Current Assets",
  total_non_current_assets: "Total Non-Current Assets",
  total_assets: "Total Assets",
  accounts_payable: "Accounts Payable",
  income_tax_payable: "Income Tax Payable",
  total_tax_payable: "Total Tax Payable",
  payables: "Payables",
  payables_and_accrued_expenses: "Payables and Accrued Expenses",
  commercial_paper: "Commercial Paper",
  other_current_borrowings: "Other Current Borrowings",
  current_debt: "Current Debt",
  current_capital_lease_obligation: "Current Capital Lease Obligation",
  current_debt_and_capital_lease_obligation:
    "Current Debt and Capital Lease Obligation",
  current_deferred_revenue: "Current Deferred Revenue",
  current_deferred_liabilities: "Current Deferred Liabilities",
  other_current_liabilities: "Other Current Liabilities",
  current_liabilities: "Current Liabilities",
  long_term_debt: "Long-Term Debt",
  long_term_capital_lease_obligation: "Long-Term Capital Lease Obligation",
  long_term_debt_and_capital_lease_obligation:
    "Long-Term Debt and Capital Lease Obligation",
  tradeand_other_payables_non_current: "Trade and Other Payables (Non-Current)",
  other_non_current_liabilities: "Other Non-Current Liabilities",
  total_non_current_liabilities_net_minority_interest:
    "Total Non-Current Liabilities (Net Minority Interest)",
  total_liabilities_net_minority_interest:
    "Total Liabilities (Net Minority Interest)",
  common_stock: "Common Stock",
  capital_stock: "Capital Stock",
  retained_earnings: "Retained Earnings",
  other_equity_adjustments: "Other Equity Adjustments",
  gains_losses_not_affecting_retained_earnings:
    "Gains (Losses) Not Affecting Retained Earnings",
  total_common_equity: "Total Common Equity",
  total_equity_non_controlling_interests:
    "Total Equity (Non-Controlling Interests)",
  total_capitalization: "Total Capitalization",
  common_stock_equity: "Common Stock Equity",
  capital_lease_obligations: "Capital Lease Obligations",
  net_tangible_assets: "Net Tangible Assets",
  working_capital: "Working Capital",
  invested_capital: "Invested Capital",
  tangible_book_value: "Tangible Book Value",
  total_debt: "Total Debt",
  net_debt: "Net Debt",
  share_issued: "Shares Issued",
  ordinary_shares_number: "Ordinary Shares (Number)",
  treasury_shares_number: "Treasury Shares (Number)",

  net_income_from_continuing_operations:
    "Net Income from Continuing Operations",
  depreciation_and_amortization: "Depreciation and Amortization",
  depreciation_amortization_depletion:
    "Depreciation, Amortization, and Depletion",
  deferred_income_tax: "Deferred Income Tax",
  deferred_tax: "Deferred Tax",
  stock_based_compensation: "Stock-Based Compensation",
  other_non_cash_items: "Other Non-Cash Items",
  changes_in_account_receivables: "Changes in Account Receivables",
  change_in_receivables: "Change in Receivables",
  change_in_inventory: "Change in Inventory",
  change_in_account_payable: "Change in Account Payable",
  change_in_payable: "Change in Payable",
  change_in_payables_and_accrued_expense:
    "Change in Payables and Accrued Expense",
  change_in_other_current_assets: "Change in Other Current Assets",
  change_in_other_current_liabilities: "Change in Other Current Liabilities",
  change_in_other_working_capital: "Change in Other Working Capital",
  change_in_working_capital: "Change in Working Capital",
  cash_flow_from_continuing_operating_activities:
    "Cash Flow from Continuing Operating Activities",
  operating_cash_flow: "Operating Cash Flow",
  investments_in_property_plant_and_equipment:
    "Investments in Property, Plant, and Equipment",
  net_ppe_purchase_and_sale: "Net PPE Purchase and Sale",
  purchase_of_business: "Purchase of Business",
  net_business_purchase_and_sale: "Net Business Purchase and Sale",
  purchase_of_investment: "Purchase of Investment",
  sale_of_investment: "Sale of Investment",
  net_investment_purchase_and_sale: "Net Investment Purchase and Sale",
  net_other_investing_changes: "Net Other Investing Changes",
  cash_flow_from_continuing_investing_activities:
    "Cash Flow from Continuing Investing Activities",
  investing_cash_flow: "Investing Cash Flow",
  long_term_debt_issuance: "Long-Term Debt Issuance",
  long_term_debt_payments: "Long-Term Debt Payments",
  net_long_term_debt_issuance: "Net Long-Term Debt Issuance",
  net_short_term_debt_issuance: "Net Short-Term Debt Issuance",
  net_issuance_payments_of_debt: "Net Issuance (Payments) of Debt",
  issuance_of_common_equity: "Issuance of Common Equity",
  repurchase_of_common_equity: "Repurchase of Common Equity",
  net_common_stock_issuance: "Net Common Stock Issuance",
  common_stock_dividend_paid: "Common Stock Dividend Paid",
  cash_dividends_paid: "Cash Dividends Paid",
  net_other_financing_charges: "Net Other Financing Charges",
  cash_flow_from_continuing_financing_activities:
    "Cash Flow from Continuing Financing Activities",
  financing_cash_flow: "Financing Cash Flow",
  net_change_in_cash_and_equivalents: "Net Change in Cash and Equivalents",
  beginning_cash_position: "Beginning Cash Position",
  end_cash_position: "End Cash Position",
  income_tax_paid_supplemental_data: "Income Tax Paid (Supplemental Data)",
  interest_paid_supplemental_data: "Interest Paid (Supplemental Data)",
  capital_expenditure: "Capital Expenditure",
  issuance_of_capital_stock: "Issuance of Capital Stock",
  issuance_of_debt: "Issuance of Debt",
  repayment_of_debt: "Repayment of Debt",
  repurchase_of_capital_stock: "Repurchase of Capital Stock",
  free_cash_flow: "Free Cash Flow",
};
