import { GroupOption } from "react-tailwindcss-select/dist/components/type";

export const industries = {
  Energy: ["Oil, Gas & Consumable Fuels", "Energy Equipment & Services"],
  Materials: [
    "Chemicals",
    "Construction Materials",
    "Containers & Packaging",
    "Metals & Mining",
    "Paper & Forest Products",
  ],
  Industrials: [
    "Aerospace & Defense",
    "Building Products",
    "Construction & Engineering",
    "Electrical Equipment",
    "Industrial Conglomerates",
    "Machinery",
    "Trading Companies & Distributors",
    "Commercial Services & Supplies",
    "Professional Services",
    "Air Freight & Logistics",
    "Airlines",
    "Marine",
    "Road & Rail",
    "Transportation Infrastructure",
  ],
  "Consumer Discretionary": [
    "Auto Components",
    "Automobiles",
    "Household Durables",
    "Leisure Products",
    "Textiles, Apparel & Luxury Goods",
    "Hotels, Restaurants & Leisure",
    "Diversified Consumer Services",
    "Media",
    "Distributors",
    "Internet & Direct Marketing Retail",
    "Multiline Retail",
    "Specialty Retail",
  ],
  "Consumer Staples": [
    "Beverages",
    "Food & Staples Retailing",
    "Food Products",
    "Household Products",
    "Personal Products",
    "Tobacco",
  ],
  "Health Care": [
    "Health Care Equipment & Supplies",
    "Health Care Providers & Services",
    "Health Care Technology",
    "Biotechnology",
    "Pharmaceuticals",
    "Life Sciences Tools & Services",
  ],
  Financials: [
    "Banks",
    "Thrifts & Mortgage Finance",
    "Diversified Financial Services",
    "Consumer Finance",
    "Capital Markets",
    "Mortgage REITs",
    "Insurance",
  ],
  "Information Technology": [
    "IT Services",
    "Software",
    "Communications Equipment",
    "Technology Hardware, Storage & Peripherals",
    "Electronic Equipment, Instruments & Components",
    "Semiconductors & Semiconductor Equipment",
  ],
  "Communication Services": [
    "Diversified Telecommunication Services",
    "Wireless Telecommunication Services",
    "Media",
    "Entertainment",
    "Interactive Media & Services",
  ],
  Utilities: [
    "Electric Utilities",
    "Gas Utilities",
    "Multi-Utilities",
    "Water Utilities",
    "Independent Power and Renewable Electricity Producers",
  ],
  "Real Estate": ["Equity REITs", "Real Estate Management & Development"],
};

export const stockFiltersMap = {
  industry: "Industry",
  sector: "Sector",
  exchange: "Exchange",
  pe_ratio: "P/E Ratio (Trailing)",
  pe_ratio_forward: "P/E Ratio (Forward)",
  ps_ratio: "P/S Ratio",
  ev_ebitda: "EV/EBITDA",
  pb_ratio: "P/B Ratio",
  dividend_yield: "Dividend Yield",
  revenue_growth_yoy: "Revenue Growth (1Y)",
  revenue_growth_3y: "Revenue Growth (3Y)",
  revenue_growth_5y: "Revenue Growth (5Y)",
  eps_growth_yoy: "EPS Growth (1Y)",
  eps_growth_3y: "EPS Growth (3Y)",
  eps_growth_5y: "EPS Growth (5Y)",
  gross_margin: "Gross Margin",
  operating_margin: "Operating Margin",
  net_profit_margin: "Net Profit Margin",
  roe: "Return on Equity (ROE)",
  roa: "Return on Assets (ROA)",
  roic: "Return on Invested Capital (ROIC)",
  debt_to_equity: "Debt/Equity Ratio",
  current_ratio: "Current Ratio",
  quick_ratio: "Quick Ratio",
  rsi: "Relative Strength Index (RSI)",
  "52_week_high_low": "52-Week High/Low",
  short_interest_ratio: "Short Interest Ratio",
  analyst_rating: "Analyst Rating",
  market_cap: "Market Capitalization",
  avg_daily_volume: "Average Daily Trading Volume",
  beta: "Beta (Volatility)",
};

export const STOCK_FILTERS = [
  {
    label: "Basics",
    options: ["industry", "sector", "exchange"],
  },
  {
    label: "Valuation",
    options: [
      "pe_ratio",
      "pe_ratio_forward",
      "ps_ratio",
      "ev_ebitda",
      "pb_ratio",
      "dividend_yield",
    ],
  },
  {
    label: "Growth",
    options: [
      "revenue_growth_yoy",
      "revenue_growth_3y",
      "revenue_growth_5y",
      "eps_growth_yoy",
      "eps_growth_3y",
      "eps_growth_5y",
    ],
  },
  {
    label: "Profitability",
    options: [
      "gross_margin",
      "operating_margin",
      "net_profit_margin",
      "roe",
      "roa",
      "roic",
    ],
  },
  {
    label: "Financial Health",
    options: ["debt_to_equity", "current_ratio", "quick_ratio"],
  },
  {
    label: "Momentum",
    options: ["rsi", "52_week_high_low"],
  },
  {
    label: "Market Sentiment",
    options: ["short_interest_ratio", "analyst_rating"],
  },
  {
    label: "Other",
    options: ["market_cap", "avg_daily_volume", "beta"],
  },
];
